# Generated by Django 5.0.7 on 2024-07-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=22, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
